# Generated by Django 6.0.2 on 2026-02-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cis', models.CharField(max_length=8, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('forme_pharmaceutique', models.CharField(blank=True, max_length=255)),
                ('laboratoire', models.CharField(blank=True, max_length=255)),
                ('substance_active', models.CharField(blank=True, max_length=255)),
                ('source_reglementaire', models.CharField(blank=True, max_length=50)),
                ('date_mise_a_jour', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
