# Generated by Django 6.0.2 on 2026-02-09 19:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='cis',
            field=models.CharField(max_length=10, unique=True, verbose_name='Code CIS'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='date_mise_a_jour',
            field=models.DateField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicament',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='Nom du médicament'),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='source_reglementaire',
            field=models.CharField(default='BDPM', max_length=50),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='substance_active',
            field=models.TextField(blank=True),
        ),
    ]
